require File.dirname(__FILE__) + "/lib/boot_inquirer"
source "https://rubygems.org"
ruby "2.1.5"

gem "rails", "~> 4.2.4 "
gem "pg", "~> 0.18.2"
gem "sass-rails", "~> 5.0.4"
gem "uglifier", "~> 2.5.3"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails", "~> 3.1.1"
gem "jbuilder", "~> 2.1.3"
gem "sdoc", "~> 0.4.1", group: :doc
gem "responders", "~> 2.1.0"
gem "rb-readline", "~> 0.5.1", require: false
gem "seedbank", "~> 0.3.0"
gem "paper_trail", "~> 4.0.0"
gem "devise", "~> 3.5.2"
gem "devise-async", "~> 0.9.0"
gem "sidekiq", "~> 4.2.6"
gem "sinatra", "~> 1.4.5", require: false
gem "sinatra-cross_origin", "~> 0.3.2"
gem "simple_form", "3.2.0"
gem "bootstrap-sass", "~> 3.2.0.1"
gem "kaminari", "~> 0.16.1"
gem "kaminari-bootstrap", "~> 3.0.1"
gem "ransack", "~> 1.6.6"
gem "route_translator", "~> 4.0.0"
gem "figaro", "~> 0.7.0"
gem "enum_help", "~> 0.0.9"
gem "momentjs-rails", "~> 2.8.1"
gem "bootstrap3-datetimepicker-rails", "~> 3.1.1"
gem "select2-rails", "~> 4.0.2"
gem "font-awesome-rails", "~> 4.3.0"
gem "cancancan", "~> 1.9"
gem "jquery-turbolinks", "~> 2.0.2"
gem "carrierwave", "~> 0.10.0"
gem "draper", "~> 2.1.0"
gem "ckeditor", "~> 4.1.0"
gem "paloma", "4.2.0"
gem "nested_form", "~> 0.3.2"
gem "audited-activerecord", "~> 4.0"
gem "aasm", "~> 4.11.0"
gem "prawn", "1.3.0"
gem "prawnto_2", "~> 0.2.0", require: "prawnto"
gem "prawn-table", "0.2.0"
gem "brdinheiro", "~> 3.3.0"
gem "nokogiri", "~> 1.6.7.2"
gem "time_diff", "~> 0.3.0"
gem "whenever", "~> 0.9.4"
gem "newrelic_rpm", "~> 3.9.0"
gem "savon", "~> 2.11.1"
gem "barby", "~> 0.6.2"
gem "barby-chunky_png", "~> 0.3.4"
gem "jquery-ui-rails"
gem "redis", "~> 3.3.2"
gem "redis-namespace", "~> 1.5.2"
gem "redis-objects", "~> 1.2.1"
gem "redis-rails", "~> 5.0.1"
gem "elasticsearch-model", "~> 0.1.6"
gem "elasticsearch-rails", "~> 0.1.6"
gem "business_time", "~> 0.7.3"
gem "rabl", "~> 0.11.4"
gem "oj", "~> 2.11.1"
gem "nested-hstore", "~> 0.1.2"
gem "immigrant", "~> 0.2.0"
gem "file_validators", "~> 1.2.0"
gem "pdf-reader", "~> 1.4"
gem "wicked_pdf", "~> 0.11.0"
gem "wkhtmltopdf-binary", "~> 0.9.9.3"
gem "bootstrap-tooltip-rails", "~> 0.1"
gem "chrono_logger", "~> 1.0.0"
gem "rubyzip", ">= 1.0.0"
gem "zip-zip", "~>0.3"
gem "redirect_on_back", "~> 1.0.0"
gem "airbrake", "~> 4.1.0"
gem "jquery-minicolors-rails", "~> 2.1.4.0"
gem "yaml_db", "~> 0.3.0"
gem "pivotal-tracker", "~> 0.5.13"
gem "nestive", "~> 0.6.0"
gem "gon", "6.0.1"
gem "bourbon", "3.2.4"
gem "remotipart", "~>1.2.1"
gem "time_difference", "~> 0.4.2"
gem "roo", "~> 2.1.1"
gem "countries", "~> 1.2.2", require: "countries/global"
gem "grape", "~> 0.14.0"
gem "active_model_serializers", "~> 0.9.3"
gem "haml", "~> 4.0"
gem "execjs", "~> 2.6.0"
gem "therubyracer", "~> 0.12.2"
gem "addressable", "~> 2.3.8"
gem "grape-jbuilder", "~> 0.2.0"
gem "mina-sidekiq",  "0.4.1"
gem "geocoder", "~> 1.3", ">= 1.3.7"
gem "dragula-rails", "~> 3.5", ">= 3.5.3"

group :development, :test do
  gem "faker", "~> 1.5.0"
  gem "rack_session_access", "~> 0.1.1"
  gem "forgery", "~> 0.6.0"
  gem "pry-byebug", "~> 1.3.2"
  gem "rspec-rails", "~> 3.3.3"
  gem "factory_girl_rails", "~> 4.5.0"
  gem "rspec-retry", "~> 0.4.0"
end

group :development do
  gem "guard-rspec", "~> 4.3.1"
  gem "guard", "~> 2.6.1"
  gem "guard-livereload", "~> 2.3.0"
  gem "rack-livereload", "~> 0.3.15"
  gem "binding_of_caller", "~> 0.7.2"
  gem "better_errors", "~> 1.1.0"
  gem "brakeman", "~> 2.6.1"
  gem "rails_best_practices", "~> 1.15.4", require: false
  gem "rubocop", "~> 0.25.0", require: false
  gem "bullet", "~> 4.13.1"
  gem "puma", "~> 2.9.0"
  gem "spring", "~> 1.1.3"
  gem "mina", "~> 0.3.0"
  gem "mina-multistage", "~> 0.1.1", require: false
  gem "letter_opener_web", "~> 1.2.2"
  gem "hirb", "~> 0.7.2"
  gem "quiet_assets", "~> 1.1.0"
  gem "seed_dump", "~> 3.2.4"
end

group :test do
  gem "timecop", "~> 0.8.0"
  gem "capybara", "~> 2.4.1"
  gem "capybara-webkit", "~> 1.3.0"
  gem "capybara_discoball", "~> 0.0.1"
  gem "database_cleaner", "~> 1.3.0"
  gem "email_spec", "~> 1.6.0"
  gem "shoulda-matchers", "2.6.1"
  gem "webmock", "~> 1.18.0"
  gem "enumerize-matchers", "~> 0.0.1"
  gem "rspec_candy", "~> 0.3.1"
  gem "rspec-activemodel-mocks", "~> 1.0.1"
  gem "vcr", "~> 2.9.2"
  gem "simplecov", "~> 0.9.0", require: false
  gem "simplecov-badge", "~> 2.0.2", require: false
  gem "formulaic", "~> 0.1.0"
  gem "poltergeist", "~> 1.6.0"
  gem "pdf-inspector", "~> 1.1.0", require: "pdf/inspector"
  gem "fakeredis", "~> 0.6.0", require: "fakeredis/rspec"
  gem "shoulda-callback-matchers", "~> 1.1.1"
  gem "test_after_commit", "~> 1.0.0"
end

group :production do
  gem "unicorn", "~> 4.8.3"
end

gemspec path: "apps/shared"
BootInquirer.each_active_app do |app|
  gemspec path: "apps/#{app.gem_name}"
end
